name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install and configure Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python - --yes
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - run: poetry install --no-interaction

      - run: sudo apt install -y exiftool

      - name: Check ExifTool version
        run: exiftool -ver

      - name: Run linting
        run: |
          poetry run isort . --diff
          poetry run black . --diff
          poetry run flake8

      - name: Run unit & integration tests
        run: |
          poetry run coverage run -m pytest tests
          poetry run coverage report --fail-under 49
